name: goimports
on:
  push:
    branches:
      - master
  pull_request:
jobs:

  gofmt:
    name: Run goimports
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    
    - name: Get goimports
      run: go get golang.org/x/tools/cmd/goimports

    - name: goimports
      run: |
        if [ "$(find . -iname '*.go' | xargs goimports -l)" ]
        then
          find . -iname '*.go' | xargs goimports -d
          exit 1
        fi
